package com.cd.domain;

public class AsiaHandicap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_handicap.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_handicap.handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Double handicap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_handicap.home_club_odds
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Double homeClubOdds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_handicap.guest_club_odds
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Double guestClubOdds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_handicap.time
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_handicap.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_handicap.match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer matchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_handicap.id
     *
     * @return the value of asia_handicap.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_handicap.id
     *
     * @param id the value for asia_handicap.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_handicap.handicap
     *
     * @return the value of asia_handicap.handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Double getHandicap() {
        return handicap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_handicap.handicap
     *
     * @param handicap the value for asia_handicap.handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setHandicap(Double handicap) {
        this.handicap = handicap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_handicap.home_club_odds
     *
     * @return the value of asia_handicap.home_club_odds
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Double getHomeClubOdds() {
        return homeClubOdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_handicap.home_club_odds
     *
     * @param homeClubOdds the value for asia_handicap.home_club_odds
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setHomeClubOdds(Double homeClubOdds) {
        this.homeClubOdds = homeClubOdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_handicap.guest_club_odds
     *
     * @return the value of asia_handicap.guest_club_odds
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Double getGuestClubOdds() {
        return guestClubOdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_handicap.guest_club_odds
     *
     * @param guestClubOdds the value for asia_handicap.guest_club_odds
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setGuestClubOdds(Double guestClubOdds) {
        this.guestClubOdds = guestClubOdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_handicap.time
     *
     * @return the value of asia_handicap.time
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_handicap.time
     *
     * @param time the value for asia_handicap.time
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_handicap.company_id
     *
     * @return the value of asia_handicap.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_handicap.company_id
     *
     * @param companyId the value for asia_handicap.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_handicap.match_id
     *
     * @return the value of asia_handicap.match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_handicap.match_id
     *
     * @param matchId the value for asia_handicap.match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setMatchId(Integer matchId) {
        this.matchId = matchId;
    }
}