package com.cd.domain;

public class AsiaUnionEurope {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_union_europe.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_union_europe.asia_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer asiaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_union_europe.europe_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer europeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asia_union_europe.match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer matchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_union_europe.id
     *
     * @return the value of asia_union_europe.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_union_europe.id
     *
     * @param id the value for asia_union_europe.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_union_europe.asia_id
     *
     * @return the value of asia_union_europe.asia_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getAsiaId() {
        return asiaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_union_europe.asia_id
     *
     * @param asiaId the value for asia_union_europe.asia_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setAsiaId(Integer asiaId) {
        this.asiaId = asiaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_union_europe.europe_id
     *
     * @return the value of asia_union_europe.europe_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getEuropeId() {
        return europeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_union_europe.europe_id
     *
     * @param europeId the value for asia_union_europe.europe_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setEuropeId(Integer europeId) {
        this.europeId = europeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asia_union_europe.match_id
     *
     * @return the value of asia_union_europe.match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asia_union_europe.match_id
     *
     * @param matchId the value for asia_union_europe.match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setMatchId(Integer matchId) {
        this.matchId = matchId;
    }
}