package com.cd.domain;

public class Default {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column default.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column default.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column default.valid
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column default.id
     *
     * @return the value of default.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column default.id
     *
     * @param id the value for default.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column default.company_id
     *
     * @return the value of default.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column default.company_id
     *
     * @param companyId the value for default.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column default.valid
     *
     * @return the value of default.valid
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column default.valid
     *
     * @param valid the value for default.valid
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}