package com.cd.domain;

public class EuropeHandicap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.win
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Double win;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.draw
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Double draw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.lose
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Double lose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.win_percent
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer winPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.draw_percent
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer drawPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.lose_percent
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer losePercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.time
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column europe_handicap.match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer matchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.id
     *
     * @return the value of europe_handicap.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.id
     *
     * @param id the value for europe_handicap.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.company_id
     *
     * @return the value of europe_handicap.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.company_id
     *
     * @param companyId the value for europe_handicap.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.win
     *
     * @return the value of europe_handicap.win
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Double getWin() {
        return win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.win
     *
     * @param win the value for europe_handicap.win
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setWin(Double win) {
        this.win = win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.draw
     *
     * @return the value of europe_handicap.draw
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Double getDraw() {
        return draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.draw
     *
     * @param draw the value for europe_handicap.draw
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setDraw(Double draw) {
        this.draw = draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.lose
     *
     * @return the value of europe_handicap.lose
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Double getLose() {
        return lose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.lose
     *
     * @param lose the value for europe_handicap.lose
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setLose(Double lose) {
        this.lose = lose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.win_percent
     *
     * @return the value of europe_handicap.win_percent
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getWinPercent() {
        return winPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.win_percent
     *
     * @param winPercent the value for europe_handicap.win_percent
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setWinPercent(Integer winPercent) {
        this.winPercent = winPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.draw_percent
     *
     * @return the value of europe_handicap.draw_percent
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getDrawPercent() {
        return drawPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.draw_percent
     *
     * @param drawPercent the value for europe_handicap.draw_percent
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setDrawPercent(Integer drawPercent) {
        this.drawPercent = drawPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.lose_percent
     *
     * @return the value of europe_handicap.lose_percent
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getLosePercent() {
        return losePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.lose_percent
     *
     * @param losePercent the value for europe_handicap.lose_percent
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setLosePercent(Integer losePercent) {
        this.losePercent = losePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.time
     *
     * @return the value of europe_handicap.time
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.time
     *
     * @param time the value for europe_handicap.time
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column europe_handicap.match_id
     *
     * @return the value of europe_handicap.match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getMatchId() {
        return matchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column europe_handicap.match_id
     *
     * @param matchId the value for europe_handicap.match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setMatchId(Integer matchId) {
        this.matchId = matchId;
    }
}