package com.cd.domain;

public class Feature {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column features.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column features.feature_name
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private String featureName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column features.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column features.handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Byte handicap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column features.final
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private String finalScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column features.id
     *
     * @return the value of features.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column features.id
     *
     * @param id the value for features.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column features.feature_name
     *
     * @return the value of features.feature_name
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public String getFeatureName() {
        return featureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column features.feature_name
     *
     * @param featureName the value for features.feature_name
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setFeatureName(String featureName) {
        this.featureName = featureName == null ? null : featureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column features.company_id
     *
     * @return the value of features.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column features.company_id
     *
     * @param companyId the value for features.company_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column features.handicap
     *
     * @return the value of features.handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Byte getHandicap() {
        return handicap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column features.handicap
     *
     * @param handicap the value for features.handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setHandicap(Byte handicap) {
        this.handicap = handicap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column features.final
     *
     * @return the value of features.final
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public String getFinal() {
        return this.finalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column features.final
     *
     * @param final the value for features.final
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setFinalScore(String finalScore) {
        this.finalScore = finalScore;
    }
}