package com.cd.domain;

public class League {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column league.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column league.name
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column league.id
     *
     * @return the value of league.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column league.id
     *
     * @param id the value for league.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column league.name
     *
     * @return the value of league.name
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column league.name
     *
     * @param name the value for league.name
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}