package com.cd.domain;

public class Match {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.home_club
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private String homeClub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.guest_club
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private String guestClub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.home_score
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Byte homeScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.guest_score
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Byte guestScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.league_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer leagueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.match_time
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Integer matchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.importance
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Byte importance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.multi
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Byte multi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.last_match_match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private String lastMatchMatchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.final_odds
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Double finalOdds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.final_surprise
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private Byte finalSurprise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column matches.feature_ids
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    private String featureIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.id
     *
     * @return the value of matches.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.id
     *
     * @param id the value for matches.id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.home_club
     *
     * @return the value of matches.home_club
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public String getHomeClub() {
        return homeClub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.home_club
     *
     * @param homeClub the value for matches.home_club
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setHomeClub(String homeClub) {
        this.homeClub = homeClub == null ? null : homeClub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.guest_club
     *
     * @return the value of matches.guest_club
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public String getGuestClub() {
        return guestClub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.guest_club
     *
     * @param guestClub the value for matches.guest_club
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setGuestClub(String guestClub) {
        this.guestClub = guestClub == null ? null : guestClub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.home_score
     *
     * @return the value of matches.home_score
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Byte getHomeScore() {
        return homeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.home_score
     *
     * @param homeScore the value for matches.home_score
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setHomeScore(Byte homeScore) {
        this.homeScore = homeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.guest_score
     *
     * @return the value of matches.guest_score
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Byte getGuestScore() {
        return guestScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.guest_score
     *
     * @param guestScore the value for matches.guest_score
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setGuestScore(Byte guestScore) {
        this.guestScore = guestScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.league_id
     *
     * @return the value of matches.league_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getLeagueId() {
        return leagueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.league_id
     *
     * @param leagueId the value for matches.league_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setLeagueId(Integer leagueId) {
        this.leagueId = leagueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.match_time
     *
     * @return the value of matches.match_time
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Integer getMatchTime() {
        return matchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.match_time
     *
     * @param matchTime the value for matches.match_time
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setMatchTime(Integer matchTime) {
        this.matchTime = matchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.importance
     *
     * @return the value of matches.importance
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Byte getImportance() {
        return importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.importance
     *
     * @param importance the value for matches.importance
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setImportance(Byte importance) {
        this.importance = importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.multi
     *
     * @return the value of matches.multi
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Byte getMulti() {
        return multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.multi
     *
     * @param multi the value for matches.multi
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setMulti(Byte multi) {
        this.multi = multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.last_match_match_id
     *
     * @return the value of matches.last_match_match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public String getLastMatchMatchId() {
        return lastMatchMatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.last_match_match_id
     *
     * @param lastMatchMatchId the value for matches.last_match_match_id
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setLastMatchMatchId(String lastMatchMatchId) {
        this.lastMatchMatchId = lastMatchMatchId == null ? null : lastMatchMatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.final_odds
     *
     * @return the value of matches.final_odds
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Double getFinalOdds() {
        return finalOdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.final_odds
     *
     * @param finalOdds the value for matches.final_odds
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setFinalOdds(Double finalOdds) {
        this.finalOdds = finalOdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.final_surprise
     *
     * @return the value of matches.final_surprise
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public Byte getFinalSurprise() {
        return finalSurprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.final_surprise
     *
     * @param finalSurprise the value for matches.final_surprise
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setFinalSurprise(Byte finalSurprise) {
        this.finalSurprise = finalSurprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column matches.feature_ids
     *
     * @return the value of matches.feature_ids
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public String getFeatureIds() {
        return featureIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column matches.feature_ids
     *
     * @param featureIds the value for matches.feature_ids
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    public void setFeatureIds(String featureIds) {
        this.featureIds = featureIds == null ? null : featureIds.trim();
    }
}