package com.cd.dao;


import com.cd.domain.AsiaUnionEurope;

public interface AsiaUnionEuropeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_union_europe
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_union_europe
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int insert(AsiaUnionEurope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_union_europe
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int insertSelective(AsiaUnionEurope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_union_europe
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    AsiaUnionEurope selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_union_europe
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int updateByPrimaryKeySelective(AsiaUnionEurope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_union_europe
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int updateByPrimaryKey(AsiaUnionEurope record);
}