package com.cd.dao;


import com.cd.domain.AsiaHandicap;
import org.springframework.stereotype.Repository;

@Repository("asiaHandicapDao")
public interface AsiaHandicapDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int insert(AsiaHandicap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int insertSelective(AsiaHandicap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    AsiaHandicap selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int updateByPrimaryKeySelective(AsiaHandicap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asia_handicap
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int updateByPrimaryKey(AsiaHandicap record);
}