package com.cd.dao;


import com.cd.domain.Default;

public interface DefaultDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table default
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table default
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int insert(Default record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table default
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int insertSelective(Default record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table default
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    Default selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table default
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int updateByPrimaryKeySelective(Default record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table default
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int updateByPrimaryKey(Default record);
}