package com.cd.dao;


import com.cd.domain.League;

public interface LeagueDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table league
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table league
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int insert(League record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table league
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int insertSelective(League record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table league
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    League selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table league
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int updateByPrimaryKeySelective(League record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table league
     *
     * @mbggenerated Sat Jan 31 12:40:45 CST 2015
     */
    int updateByPrimaryKey(League record);
}